.TH "Camera_OV767X" 3 "Version 0.1.0" "Pi Pico OV767X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera_OV767X
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <camera\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSCCB_OV767X\fP \fBsccb\fP"
.br
.ti -1c
.RI "\fBCameraClock_OV767X\fP \fBclk\fP"
.br
.ti -1c
.RI "\fBFormat_OV767X\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBResolution_OV767X\fP \fBresolution\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Camera Descriptor 
.SH "Field Documentation"
.PP 
.SS "\fBSCCB_OV767X\fP Camera_OV767X::sccb"
SCCB interface to camera 
.SS "\fBCameraClock_OV767X\fP Camera_OV767X::clk"
XCLK configuration for camera 
.SS "\fBFormat_OV767X\fP Camera_OV767X::format"
Color format configuration for camera 
.SS "\fBResolution_OV767X\fP Camera_OV767X::resolution"
Image resolution configuration for camera 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pi Pico OV767X from the source code\&.
