.TH "SCCB_OV767X" 3 "Version 0.1.0" "Pi Pico OV767X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCCB_OV767X
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sccb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "i2c_inst_t * \fBinst\fP"
.br
.ti -1c
.RI "uint8_t \fBdevAddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SCCB Interface Descriptor 
.SH "Field Documentation"
.PP 
.SS "i2c_inst_t* SCCB_OV767X::inst"
I2C instance that is connected to the camera 
.SS "uint8_t SCCB_OV767X::devAddr"
SCCB address of the camera 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pi Pico OV767X from the source code\&.
