.TH "include/pi-pico-ov767X/sccb.h" 3 "Version 0.1.0" "Pi Pico OV767X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pi-pico-ov767X/sccb.h \- Delclaration of simple SCCB IO functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSCCB_OV767X\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsccbReadByte\fP (\fBSCCB_OV767X\fP *sccb, uint8_t reg, uint8_t *dest)"
.br
.ti -1c
.RI "void \fBsccbWriteByte\fP (\fBSCCB_OV767X\fP *sccb, uint8_t reg, uint8_t dat)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Delclaration of simple SCCB IO functions\&. 

This file contains declaration of SCCB IO functions and descriptor structure\&. 
.PP
\fBAuthor\fP
.RS 4
kenryuS 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void sccbReadByte (\fBSCCB_OV767X\fP * sccb, uint8_t reg, uint8_t * dest)"
Read a byte from a register 
.PP
\fBParameters\fP
.RS 4
\fIsccb\fP A pointer to SCCB interface descriptor 
.br
\fIreg\fP Register address to be read from 
.br
\fIdest\fP A pointer to buffer where the retrived data is stored on 
.RE
.PP

.SS "void sccbWriteByte (\fBSCCB_OV767X\fP * sccb, uint8_t reg, uint8_t dat)"
Write a byte to a register 
.PP
\fBParameters\fP
.RS 4
\fIsccb\fP A pointer to SCCB interface descriptor 
.br
\fIreg\fP Register address to be read from 
.br
\fIdat\fP A byte of data to be written to 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pi Pico OV767X from the source code\&.
