#ifndef __PI_PICO_OV767X_CAMERA_REGS_H__
#define __PI_PICO_OV767X_CAMERA_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define OV767X_COM_CFG_CNT 48
#define OV767X_RGB565_CFG_CNT 10
#define OV767X_YUV422_CFG_CNT 10
#define OV767X_VGA_CFG_CNT 7
#define OV767X_QVGA_CFG_CNT 7
#define OV767X_QQVGA_CFG_CNT 7

extern const uint8_t OV767X_COM_CFG[OV767X_COM_CFG_CNT][2];
extern const uint8_t OV767X_RGB565_CFG[OV767X_RGB565_CFG_CNT][2];
extern const uint8_t OV767X_YUV422_CFG[OV767X_YUV422_CFG_CNT][2];
extern const uint8_t OV767X_VGA_CFG[OV767X_VGA_CFG_CNT][2];
extern const uint8_t OV767X_QVGA_CFG[OV767X_QVGA_CFG_CNT][2];
extern const uint8_t OV767X_QQVGA_CFG[OV767X_QQVGA_CFG_CNT][2];


typedef enum : uint8_t {
    GAIN,
    BLUE,
    RED,
    VREF,
    COM1,
    BAVE,
    GBAVE,
    AECHH,
    RAVE,
    COM2,
    PID,
    VER,
    COM3,
    COM4,
    COM5,
    COM6 = 0x0F,
    AECH,
    CLKRC,
    COM7,
    COM8,
    COM9,
    COM10,
    HSTART = 0x17,
    HSTOP,
    VSTART,
    VSTOP,
    PSHIFT,
    MIDH,
    MIDL,
    MVFP,
    ADCCTR0 = 0x20,
    AEW = 0x24,
    AEB,
    VPT,
    BBIAS,
    GBBIAS,
    EXHCH = 0x2A,
    EXHCL,
    RBIAS,
    ADVFL,
    ADVFH,
    YAVE,
    HSYST,
    HSYEN,
    HREF,
    CHLF,
    ARBLM,
    ADC = 0x37,
    ACOM,
    OFON,
    TSLB,
    COM11,
    COM12,
    COM13,
    COM14,
    EDGE,
    COM15,
    COM16,
    COM17,
    REG4B = 0x4B,
    DNSTH,
    MTX1 = 0x4F,
    MTX2,
    MTX3,
    MTX4,
    MTX5,
    MTX6,
    BRIGHT,
    CONTRAS,
    CONTRAS_CENTER,
    MTXS,
    LCC1 = 0x62,
    LCC2,
    LCC3,
    LCC4,
    LCC5,
    MANU,
    MANV,
    GFIX,
    GGAIN,
    DBLV,
    AWBCTR3,
    AWBCTR2,
    AWBCTR1,
    AWBCTR0,
    SCALING_XSC,
    SCALING_YSC,
    SCALING_DCWCTL,
    SCALING_PCLK_DIV,
    REG74,
    REG75,
    REG76,
    REG77,
    SLOP = 0x7A,
    GAM1,
    GAM2,
    GAM3,
    GAM4,
    GAM5,
    GAM6,
    GAM7,
    GAM8,
    GAM9,
    GAM10,
    GAM11,
    GAM12,
    GAM13,
    GAM14,
    GAM15,
    REG444 = 0x8C,
    DM_LNL = 0x92,
    DM_LNH,
    LCC6,
    LCC7,
    BD50ST = 0x9D,
    BD60ST,
    HAECC1,
    HAECC2,
    SCALING_PCLK_DELAY = 0xA2,
    NT_CTRL = 0xA4,
    BD50MAX,
    HAECC3,
    HAECC4,
    HAECC5,
    HAECC6,
    HAECC7,
    BD60MAX,
    STR_OPT,
    STR_R,
    STR_G,
    STR_B,
    ABLC1 = 0xB1,
    THL_ST = 0xB3,
    THL_DLT = 0xB5,
    AD_CHB = 0xBE,
    AD_CHR,
    AD_CHGB,
    AD_CHGR,
    SATCTR = 0xC9,
    REGCA, // Beyond this, OV7675 settings.
    REFCF = 0xCF,
    RADCO = 0xD4,
    RPWC2 = 0xDC,
    REGE1 = 0xE1,
    RDSP0 = 0xE8,
    RDSP2 = 0xEA,
    RDSP3,
    RDSP4
} OV767X_Registers;

#ifdef __cplusplus
}
#endif

#endif // __PI_PICO_OV767X_CAMERA_REGS_H__
